---
name: PR Checks

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    environment: prototype
    # Allow failing during development
    continue-on-error: true
    env:
      NCBI_EMAIL: ${{ secrets.NCBI_EMAIL }}
      NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '${{ env.UV_VERSION }}'

      - name: Install dependencies
        run: |
          uv sync

      - name: Unit Test
        run: |
          uv run pytest tests/unit --cov=src --cov-report=term --cov-report=html

      - name: Upload coverage report
        continue-on-error: true
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: htmlcov
          retention-days: 14

      - name: Integration Test
        continue-on-error: true
        env:
          OPENAI_API_KEY: ${{ secrets.APIKEY }}
        run: |
          uv run pytest tests/integration -m integration

      - name: Format
        continue-on-error: true
        run: |
          uv run ruff format --diff

      - name: Lint
        continue-on-error: true
        run: |
          uv run ruff check

  typecheck:
    runs-on: ubuntu-latest
    environment: prototype
    # Allow failing during development
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '${{ env.UV_VERSION }}'

      - name: Install dependencies
        run: |
          uv sync

      - name: Type check
        run: |
          uv run mypy
