---
name: Security audit

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sunday at midnight
  push:
    paths:
      - 'pyproject.toml'
      - '.github/workflows/security.yml'

jobs:
  audit:
    runs-on: ubuntu-latest
    environment: prototype
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: Install security tools
        run: uv sync --group security

      - name: pip-audit dependencies
        continue-on-error: true # Don't block on vulnerabilities during development
        run: uv run pip-audit

      - name: Run Ruff security checks
        continue-on-error: true
        run: |
          uv run ruff check --select=S --statistics
